### ISSUE TITLE
Rewrite description

### ISSUE THREAD

**Issue by veronicapfio** [nathan-osman/chronosnap#14]
Please change the word "images" in the description to "Photos"
"
Simple yet intuitive Android application for capturing a sequence of images at regular intervals.
"

**Comment by nathan-osman** [comment]
Which description - on the Play Store?

**Comment by veronicapfio** [comment]
Sorry to be too grammatic. Please replace the word "images" by "Photos" on the github main page. 
"Simple yet intuitive Android application for capturing a sequence of images at regular intervals."

Though many people have slowly started to use images but these are actually photos. Also can you rewrite it to "Simple yet intuitive Android application for capturing sequence of photos from Camera at regular intervals". Without "Camera" it is very difficult to find it. I find that "F-droid" store uses your description.

Edit: I managed to get f-droid changed: https://gitlab.com/fdroid/fdroiddata/commit/5ace68
