### ISSUE TITLE
Custom capture interval

### ISSUE THREAD

**Issue by nathan-osman** [nathan-osman/chronosnap#2]
As it stands now, the user is limited to the following options for setting the capture interval:
- 5 seconds
- 10 seconds
- 1 minute
- 5 minutes
- 10 minutes

Instead, a dialog similar to the following should be displayed:

![](http://i.stack.imgur.com/k1ztT.png)

This would allow the user to specify both the amount and the unit.

**Comment by sravan953** [comment]
Hey, check out  my pull-request regarding this feature!
